/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Koudelka)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800A0DFCu
#define func_800A0DFC BootEntry  /* alias */
